version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: breizh
    volumes:
      - .:/var/www/html:ro
    ports:
      - 8080:80
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: y=vhk$dZL?2C+52
      MYSQL_DATABASE: breizhsecuDB
      MYSQL_USER: breizhman
      MYSQL_PASSWORD: breizhmanPassword
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  mysql_data: